/* eslint-disable import/no-mutable-exports */
// eslint-disable-next-line no-var
export var permissions = {
     read_user:false ,
     edit_user:false ,
     delete_user:false ,
     create_user:false ,
     read_org:false ,
     edit_org:false ,
     delete_org:false ,
     create_org:false ,
     read_project:false ,
     edit_project:false ,
     delete_project:false ,
     create_project:false ,
     read_phase:false ,
     edit_phase:false ,
     delete_phase:false ,
     create_phase:false ,
     read_livrable:false ,
     edit_livrable:false ,
     delete_livrable:false ,
     create_livrable:false ,
     read_role:false ,
     edit_role:false ,
     delete_role:false ,
     create_role:false ,
}